### ISSUE TITLE
Quark, Thaumcraft and Embers compatibility.

### ISSUE THREAD

**Issue by Xorbah** [cleverpanda/Divergent-Underground#1]
Title. Would be really nice to see these mods make their way into the mod. Loving it so far!

**Comment by cleverpanda** [comment]
Embers is dead and Thaumcraft does not require support

**Comment by Xorbah** [comment]
Embers...isn't dead.

https://minecraft.curseforge.com/projects/embers-rekindled?gameCategorySlug=mc-mods&projectID=300777


It's been taken up by Bordlistian for quite some time.

**Comment by Xorbah** [comment]
Also, since my other issues thread was closed (As I was unsure of which issues tab you were keeping track of) Is it possible for Ice and Fire to receive support for its silver ore?

**Comment by cleverpanda** [comment]
Maybe, I need to look at it. Please make a separate issue. multiple mods in one issue makes it impossible to cross off things once I add them.

Quark is done and will be in the next version
