### ISSUE TITLE
[Compatibility/Enhancement]: Add similar support for Marble/Limestone/Basalt for the following mods

### ISSUE THREAD

**Issue by Lanse505** [cleverpanda/Divergent-Underground#10]
**Please feel free to contribute more mods to this list**

Mods that add Marble/Limestone/Basalt:
Basalt:
- [x] Chisel

Limestone:
- [x] Chisel

Marble:
- [ ] Astral Sorcery
- [x] Chisel

**Comment by cleverpanda** [comment]
Astral Sorcery, being a crazy mod doing fancy things, and a mod I don't play, is very low on my list.
