### ISSUE TITLE
Crash with BOP Gemstones

### ISSUE THREAD

**Issue by dariusfontan** [cleverpanda/Divergent-Underground#2]
Just got this crash while TNT-Mining a Biomes O Plenty Gemstone:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  ToolProgressionPlugin (toolprogression-core-1.12.2-1.6.5.jar)
  CreativePatchingLoader (CreativeCore_v1.9.41_mc1.12.2.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.15-universal.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.5.0-137-universal.jar)
  CorePlugin (ForgeEndertech-1.12.2-4.4.16.0-build.0306.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-88.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.2.0.jar)
  LoadingPlugin (HardcoreDarkness-MC1.12.2-2.0.jar)
  CharmLoadingPlugin (Charm-1.12.2-1.0.0-beta3.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  Quark Plugin (Quark-r1.5-148.jar)
  DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 4/30/19 7:39 PM
Description: Ticking entity

java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class biomesoplenty.api.enums.BOPGems, values=[amethyst, ruby, peridot, topaz, tanzanite, malachite, sapphire, amber]} as it does not exist in BlockStateContainer{block=divergentunderground:bop_hard_ruby_ore, properties=[hardness]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:209)
	at biomesoplenty.common.block.BlockBOPGemOre.func_176201_c(BlockBOPGemOre.java:91)
	at biomesoplenty.common.block.BlockBOPGemOre.func_180651_a(BlockBOPGemOre.java:110)
	at net.minecraft.block.Block.getDrops(Block.java:1323)
	at panda.divergentunderground.common.blocks.BlockHardStone.getDrops(BlockHardStone.java:155)
	at net.minecraft.block.Block.getDrops(Block.java:1300)
	at net.minecraft.block.Block.func_180653_a(Block.java:571)
	at net.minecraft.block.BlockOre.func_180653_a(BlockOre.java:80)
	at net.minecraft.world.Explosion.func_77279_a(Explosion.java:231)
	at net.minecraft.world.WorldServer.func_72885_a(WorldServer.java:1170)
	at net.minecraft.world.World.func_72876_a(World.java:2300)
	at net.minecraft.entity.item.EntityTNTPrimed.func_70515_d(SourceFile:99)
	at net.minecraft.entity.item.EntityTNTPrimed.func_70071_h_(SourceFile:89)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:256)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:209)
	at biomesoplenty.common.block.BlockBOPGemOre.func_176201_c(BlockBOPGemOre.java:91)
	at biomesoplenty.common.block.BlockBOPGemOre.func_180651_a(BlockBOPGemOre.java:110)
	at net.minecraft.block.Block.getDrops(Block.java:1323)
	at panda.divergentunderground.common.blocks.BlockHardStone.getDrops(BlockHardStone.java:155)
	at net.minecraft.block.Block.getDrops(Block.java:1300)
	at net.minecraft.block.Block.func_180653_a(Block.java:571)
	at net.minecraft.block.BlockOre.func_180653_a(BlockOre.java:80)
	at net.minecraft.world.Explosion.func_77279_a(Explosion.java:231)
	at net.minecraft.world.WorldServer.func_72885_a(WorldServer.java:1170)
	at net.minecraft.world.World.func_72876_a(World.java:2300)
	at net.minecraft.entity.item.EntityTNTPrimed.func_70515_d(SourceFile:99)
	at net.minecraft.entity.item.EntityTNTPrimed.func_70071_h_(SourceFile:89)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)

-- Entity being ticked --
Details:
	Entity Type: charset:tnt (pl.asie.charset.module.tweak.pushableTnt.EntityTNTImproved)
	Entity ID: 24626
	Entity Name: Block of TNT
	Entity's Exact location: -1208.51, 27.00, -290.49
	Entity's Block location: World: (-1209,27,-291), Chunk: (at 7,1,13 in -76,-19; contains blocks -1216,0,-304 to -1201,255,-289), Region: (-3,-1; contains chunks -96,-32 to -65,-1, blocks -1536,0,-512 to -1025,255,-1)
	Entity's Momentum: 0.00, -0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: New World346zhf
	All players: 1 total; [EntityPlayerMP['barttraeger'/1070, l='New World346zhf', x=-1207.75, y=33.12, z=-291.70]]
	Chunk stats: ServerChunkCache: 986 Drop: 0
	Level seed: -9174674876817016660
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: {"landScheme":"continents","tempScheme":"medium_zones","rainScheme":"medium_zones","biomeSize":"medium","amplitude":1.0,"generateBopOre":true,"generatePoisonIvy":false,"generateBerryBushes":true,"generateThorns":true,"generateQuicksand":true,"generateLiquidPoison":true,"generateHotSprings":true,"generateNetherHives":true,"generateEndFeatures":true,"mainNoiseScaleX":80.0,"mainNoiseScaleY":160.0,"mainNoiseScaleZ":80.0,"coordinateScale":684.412,"heightScale":684.412,"upperLimitScale":512.0,"lowerLimitScale":512.0}
	Level spawn location: World: (70,64,220), Chunk: (at 6,4,12 in 4,13; contains blocks 64,0,208 to 79,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 41183 game time, 181884 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 8173 (now: false), thunder time: 18161 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:256)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_211, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2636632192 bytes (2514 MB) / 6006243328 bytes (5728 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 9 total; -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2048m -Xmx6144m
	IntCache: cache: 0, tcache: 0, allocated: 1, tallocated: 93
	FML: MCP 9.42 Powered by Forge 14.23.5.2815 Optifine OptiFine_1.12.2_HD_U_E4_pre4 117 mods loaded, 117 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                      | Version            | Source                                          | Signature                                |
	|:------ |:----------------------- |:------------------ |:----------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft               | 1.12.2             | minecraft.jar                                   | None                                     |
	| LCHIJA | mcp                     | 9.42               | minecraft.jar                                   | None                                     |
	| LCHIJA | FML                     | 8.0.99.99          | forge-1.12.2-14.23.5.2815-universal.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                   | 14.23.5.2815       | forge-1.12.2-14.23.5.2815-universal.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | advancedrocketrycore    | 1                  | minecraft.jar                                   | None                                     |
	| LCHIJA | creativecoredummy       | 1.0.0              | minecraft.jar                                   | None                                     |
	| LCHIJA | ivtoolkit               | 1.3.3-1.12         | minecraft.jar                                   | None                                     |
	| LCHIJA | openmodscore            | 0.12.2             | minecraft.jar                                   | None                                     |
	| LCHIJA | dsurroundcore           | 3.5.4.3            | minecraft.jar                                   | None                                     |
	| LCHIJA | survivaltweaks          | 5.1.2              | [_raus_]_SurvivalTweaks-5.1.2-1.12.2.jar        | None                                     |
	| LCHIJA | worldstripper           | 1.6.0-1.12.2       | [_raus_]_World-Stripper-1.6.0-1.12.2.jar        | None                                     |
	| LCHIJA | forgeendertech          | 1.12.2-4.4.16.0    | ForgeEndertech-1.12.2-4.4.16.0-build.0306.jar   | None                                     |
	| LCHIJA | adlods                  | 1.12.2-1.0.4.0     | AdLods-1.12.2-1.0.4.0-build.0317.jar            | None                                     |
	| LCHIJA | redstoneflux            | 2.1.0              | RedstoneFlux-1.12-2.1.0.6-universal.jar         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | cofhcore                | 4.6.2              | CoFHCore-1.12.2-4.6.2.25-universal.jar          | None                                     |
	| LCHIJA | libvulpes               | 0.4.0.-54          | LibVulpes-1.12.2-0.4.0-54-universal.jar         | None                                     |
	| LCHIJA | advancedrocketry        | 1.5.0.-137         | AdvancedRocketry-1.12.2-1.5.0-137-universal.jar | None                                     |
	| LCHIJA | aquaculture             | 1.6.8              | Aquaculture-1.12.2-1.6.8.jar                    | None                                     |
	| LCHIJA | cd4017be_lib            | 6.3.4              | CD4017BE_lib-1.12.2-6.3.4.jar                   | None                                     |
	| LCHIJA | circuits                | 6.1.6              | AutomatedRedstone-1.12.2-6.1.6.jar              | None                                     |
	| LCHIJA | charset                 | 0.5.5.6            | Charset-Lib-0.5.5.6.jar                         | None                                     |
	| LCHIJA | jei                     | 4.13.0.218         | jei_1.12.2-4.13.0.218.jar                       | None                                     |
	| LCHIJA | quark                   | r1.5-148           | Quark-r1.5-148.jar                              | None                                     |
	| LCHIJA | autoreglib              | 1.3-28             | AutoRegLib-1.3-28.jar                           | None                                     |
	| LCHIJA | crafttweaker            | 4.1.17             | CraftTweaker2-1.12-4.1.17.jar                   | None                                     |
	| LCHIJA | base                    | 3.12.0             | base-1.12.2-3.12.0.jar                          | None                                     |
	| LCHIJA | baubles                 | 1.5.2              | Baubles-1.12-1.5.2.jar                          | None                                     |
	| LCHIJA | betteranimalsplus       | 6.0.1              | betteranimalsplus-1.12.2-6.0.1.jar              | None                                     |
	| LCHIJA | bettercombatmod         | 1.5.6              | BetterCombat-1.12.2-1.5.6.jar                   | None                                     |
	| LCHIJA | biomesoplenty           | 7.0.1.2425         | BiomesOPlenty-1.12.2-7.0.1.2425-universal.jar   | None                                     |
	| LCHIJA | better_diving           | 1.3.54             | BetterDiving-1.12.2-1.3.54.jar                  | None                                     |
	| LCHIJA | forgelin                | 1.8.2              | Forgelin-1.8.2.jar                              | None                                     |
	| LCHIJA | betterfoliage           | 2.2.0              | BetterFoliage-MC1.12-2.2.0.jar                  | None                                     |
	| LCHIJA | mantle                  | 1.12-1.3.3.49      | Mantle-1.12-1.3.3.49 (1).jar                    | None                                     |
	| LCHIJA | mcmultipart             | 2.5.3              | MCMultiPart-2.5.3.jar                           | None                                     |
	| LCHIJA | mekanism                | 1.12.2-1.2.0b2     | mekanica-1.12.2-1.2.0b2.jar                     | None                                     |
	| LCHIJA | pvj                     | 1.6.2              | ProjectVibrantJourneys-1.12.2-1.6.2.jar         | None                                     |
	| LCHIJA | toolprogression         | 1.12.2-1.6.5       | toolprogression-1.12.2-1.6.5.jar                | e631d7254e451d0360d0148cb21407d5511d45e9 |
	| LCHIJA | tconstruct              | 1.12.2-2.12.0.135  | TConstruct-1.12.2-2.12.0.135 (1).jar            | None                                     |
	| LCHIJA | engineersdecor          | 1.0.4-b5           | engineersdecor-1.12.2-1.0.4-b5.jar              | ed58ed655893ced6280650866985abcae2bf7559 |
	| LCHIJA | theoneprobe             | 1.4.28             | theoneprobe-1.12-1.4.28.jar                     | None                                     |
	| LCHIJA | immersiveengineering    | 0.12-88            | ImmersiveEngineering-0.12-88.jar                | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| LCHIJA | betterwithmods          | 1.12-2.3.20-1027   | BetterWithMods-1.12-2.3.20-1027.jar             | None                                     |
	| LCHIJA | buildinggadgets         | 2.6.8              | BuildingGadgets-2.6.8.jar                       | None                                     |
	| LCHIJA | chameleon               | 1.12-4.1.3         | Chameleon-1.12-4.1.3 (1).jar                    | None                                     |
	| LCHIJA | charm                   | 1.12.2-1.0.0-beta3 | Charm-1.12.2-1.0.0-beta3.jar                    | None                                     |
	| LCHIJA | codechickenlib          | 3.2.2.353          | CodeChickenLib-1.12.2-3.2.2.353-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | cofhworld               | 1.3.0              | CoFHWorld-1.12.2-1.3.0.6-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | compactmachines3        | 3.0.17             | compactmachines3-1.12.2-3.0.17-b267.jar         | None                                     |
	| LCHIJA | contenttweaker          | 1.12.2-4.9.1       | ContentTweaker-1.12.2-4.9.1.jar                 | None                                     |
	| LCHIJA | controlling             | 3.0.6              | Controlling-3.0.6.jar                           | None                                     |
	| LCHIJA | ctgui                   | 1.0.0              | CraftTweaker2-1.12-4.1.17.jar                   | None                                     |
	| LCHIJA | crafttweakerjei         | 2.0.3              | CraftTweaker2-1.12-4.1.17.jar                   | None                                     |
	| LCHIJA | crafttweakerutils       | 0.5                | crafttweakerutils-0.5a.jar                      | None                                     |
	| LCHIJA | creativecore            | 1.9.9              | CreativeCore_v1.9.41_mc1.12.2.jar               | None                                     |
	| LCHIJA | cyberware               | 0.2.10.15          | cyberware-1.12.2-0.2.10.15.jar                  | 67a0e286dc0d4b502f3c92ac20b953517b52d0a9 |
	| LCHIJA | divergentunderground    | 0.52.4             | Divergent-Underground-1.12-0.52.4.jar           | None                                     |
	| LCHIJA | easiervillagertrading   | 1.12.2             | easiervillagertrading-2.0.jar                   | None                                     |
	| LCHIJA | extraalchemy            | 0.3.8.6.1-release  | extraalchemy-0.3.8.6.1-release.jar              | None                                     |
	| LCHIJA | flatcoloredblocks       | mc1.12-6.7         | flatcoloredblocks-mc1.12-6.7.jar                | None                                     |
	| LCHIJA | ftblib                  | 5.4.1.93           | FTBLib-5.4.1.93.jar                             | None                                     |
	| LCHIJA | ftbutilities            | 5.4.0.89           | FTBUtilities-5.4.0.89.jar                       | None                                     |
	| LCHIJA | minecraftfuture         | 0.1.3              | future-mc-0.1.3.jar                             | None                                     |
	| LCHIJA | gobblecore              | 1.12-0.1.6.35      | GobbleCore-1.12-0.1.6.35.jar                    | None                                     |
	| LCHIJA | goodskeletonsdontstrafe | 1.0.3              | GoodSkeletonsDontStrafe-v1.0.3-1.12.2.jar       | None                                     |
	| LCHIJA | hardcoredarkness        | 2.0                | HardcoreDarkness-MC1.12.2-2.0.jar               | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCHIJA | horsepower              | 2.6.4              | HorsePower-1.12.2-2.6.4.74.jar                  | cd7e958342770a8b17c919055da42c24dfefd879 |
	| LCHIJA | mcjtylib_ng             | 3.1.1              | mcjtylib-1.12-3.1.1.jar                         | None                                     |
	| LCHIJA | immcraft                | 1.5.1              | immcraft-1.12-1.5.1.jar                         | None                                     |
	| LCHIJA | mts                     | 14.0.0             | Immersive+Vehicles-1.12.2-14.0.0.jar            | None                                     |
	| LCHIJA | immersiveposts          | 0.1.0              | ImmersivePosts-0.1.0 (1).jar                    | 0ba25d8c0ec23537afc6db926e1ea764335a33b1 |
	| LCHIJA | improvedbackpacks       | 1.12.2-1.4.0.0     | ImprovedBackpacks-1.12.2-1.4.0.0.jar            | None                                     |
	| LCHIJA | jaopca                  | 1.12.2-2.2.8.101   | JAOPCA-1.12.2-2.2.8.101 (1).jar                 | None                                     |
	| LCHIJA | oredictinit             | 1.12.2-2.2.1.71    | JAOPCA-1.12.2-2.2.8.101 (1).jar                 | None                                     |
	| LCHIJA | journeymap              | 1.12.2-5.5.2       | journeymap-1.12.2-5.5.2.jar                     | None                                     |
	| LCHIJA | jarm                    | 1.1.2              | Just A Raft Mod-1.1.2.jar                       | None                                     |
	| LCHIJA | kc                      | 1.12               | knobcontrol-1.12-4.0.20.jar                     | None                                     |
	| LCHIJA | llor                    | 1.1.6-mc1.12.2     | LLOverlayReloaded-1.1.6-mc1.12.2 (1).jar        | None                                     |
	| LCHIJA | lunatriuscore           | 1.2.0.42           | LunatriusCore-1.12.2-1.2.0.42-universal.jar     | None                                     |
	| LCHIJA | moreoverlays            | 1.14               | moreoverlays-1.14-mc1.12.2.jar                  | None                                     |
	| LCHIJA | mtsofficialpack         | 10.0.0             | MTS_Official_Pack_V10.jar                       | None                                     |
	| LCHIJA | mysticalmechanics       | 0.6                | Mystical+Mechanics-0.6.jar                      | None                                     |
	| LCHIJA | openmods                | 0.12.2             | OpenModsLib-1.12.2-0.12.2.jar                   | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LCHIJA | openblocks              | 1.8.1              | OpenBlocks-1.12.2-1.8.1.jar                     | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LCHIJA | harvestcraft            | 1.12.2zb           | Pam's HarvestCraft 1.12.2zb.jar                 | None                                     |
	| LCHIJA | patchouli               | 1.0-19             | Patchouli-1.0-19.jar                            | None                                     |
	| LCHIJA | placebo                 | 1.5.1              | Placebo-1.12.2-1.5.1.jar                        | None                                     |
	| LCHIJA | playerbosses            | 1.0                | playerbosses-1.12.2-0.1.0.jar                   | None                                     |
	| LCHIJA | playerskins             | 1.0.4              | playerskin-1.12.2-1.0.5.jar                     | None                                     |
	| LCHIJA | rustic                  | 1.1.0              | rustic-1.1.0.jar                                | None                                     |
	| LCHIJA | toughasnails            | 3.1.0.140          | ToughAsNails-1.12.2-3.1.0.140-universal.jar     | None                                     |
	| LCHIJA | primal                  | 0.6.104            | PrimalCore-1.12.2-0.6.104.jar                   | 67a0e286dc0d4b502f3c92ac20b953517b52d0a9 |
	| LCHIJA | progressiontweaks       | 1.12.2-0.3.40      | ProgressionTweaks-1.12.2-0.3.40.jar             | None                                     |
	| LCHIJA | prospects               | 0.0.1              | prospects-1.0.10.jar                            | None                                     |
	| LCHIJA | reborncore              | 3.13.12.447        | RebornCore-1.12.2-3.13.12.447-universal.jar     | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| LCHIJA | reccomplex              | 1.4.7              | RecurrentComplex-1.4.7.jar                      | None                                     |
	| LCHIJA | rwbym                   | 3.3                | rwbym-3.3.0.jar                                 | None                                     |
	| LCHIJA | scannable               | 1.6.3.24           | Scannable-MC1.12.2-1.6.3.24.jar                 | None                                     |
	| LCHIJA | scavenge                | 1.8                | Scavenge+V1.12-1.8.3.2.jar                      | None                                     |
	| LCHIJA | sereneseasons           | 1.2.15             | SereneSeasons-1.12.2-1.2.15-universal.jar       | None                                     |
	| LCHIJA | smarthud                | 2.0.2              | smarthud-2.0.2.jar                              | None                                     |
	| LCHIJA | spartanshields          | 1.5.0              | SpartanShields-1.12.2-1.5.0.jar                 | None                                     |
	| LCHIJA | storagedrawers          | 1.12-5.3.5         | StorageDrawers-1.12.2-5.3.8.jar                 | None                                     |
	| LCHIJA | storagedrawersunlimited | 1.12.2-1.0.0       | StorageDrawersUnlimited-1.12.2-1.0.0.jar        | None                                     |
	| LCHIJA | tcomplement             | ${version}         | TinkersComplement-1.12.2-0.4.0.jar              | None                                     |
	| LCHIJA | tombmanygraves          | 1.12-4.2.0         | TombManyGraves-1.12-4.2.0.jar                   | None                                     |
	| LCHIJA | treestumps              | 3.0.4              | treestumps-1.12.2-3.0.4.jar                     | None                                     |
	| LCHIJA | villagenames            | 3.0                | VillageNames-1.12.2-3.0.jar                     | None                                     |
	| LCHIJA | vtt                     | 0.6.4              | VillagerTrades-1.12-0.6.4.jar                   | None                                     |
	| LCHIJA | zephmelt                | 1.2.2              | zephmelt-1.2.2 (1).jar                          | None                                     |
	| LCHIJA | zephsift                | 1.4                | zephsift-1.4.jar                                | None                                     |
	| LCHIJA | orelib                  | 3.5.2.2            | OreLib-1.12.2-3.5.2.2.jar                       | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | dsurround               | 3.5.4.3            | DynamicSurroundings-1.12.2-3.5.4.3.jar          | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | dshuds                  | 3.5.4.0            | DynamicSurroundingsHuds-1.12.2-3.5.4.0BETA.jar  | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | llibrary                | 1.7.18             | llibrary-1.7.18-1.12.2.jar                      | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | primal_tech             | 0.3.3              | PrimalTech-0.3.3.jar                            | None                                     |
	| LCHIJA | wrapup                  | 1.12-1.1.3         | WrapUp-1.12-1.1.3.jar                           | None                                     |

	Loaded coremods (and transformers): 
OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  openmods.core.OpenModsClassTransformer
ToolProgressionPlugin (toolprogression-core-1.12.2-1.6.5.jar)
  tyra314.toolprogression.core.asm.ToolProgressionClassTransformer
CreativePatchingLoader (CreativeCore_v1.9.41_mc1.12.2.jar)
  
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.15-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
ForgelinPlugin (Forgelin-1.8.2.jar)
  
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.5.0-137-universal.jar)
  zmaster587.advancedRocketry.asm.ClassTransformer
CorePlugin (ForgeEndertech-1.12.2-4.4.16.0-build.0306.jar)
  
IELoadingPlugin (ImmersiveEngineering-core-0.12-88.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
BetterFoliageLoader (BetterFoliage-MC1.12-2.2.0.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
LoadingPlugin (HardcoreDarkness-MC1.12.2-2.0.jar)
  lumien.hardcoredarkness.asm.ClassTransformer
CharmLoadingPlugin (Charm-1.12.2-1.0.0-beta3.jar)
  svenhjol.charm.base.ClassTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
Quark Plugin (Quark-r1.5-148.jar)
  vazkii.quark.base.asm.ClassTransformer
DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
  org.orecruncher.dsurround.asm.Transformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	Pulsar/tcomplement loaded Pulses: 
		- ModuleCommons (Enabled/Forced)
		- ModuleMelter (Enabled/Not Forced)
		- ModuleArmor (Enabled/Not Forced)
		- ModuleSteelworks (Enabled/Not Forced)
		- Oredict (Enabled/Forced)

	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.13.12.447
		Runtime Debofucsation 1
		RenderEngine: 1
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['barttraeger'/1070, l='New World346zhf', x=-1207.75, y=33.12, z=-291.70]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_E4_pre4
	OptiFine Build: 20190410-123819
	Render Distance Chunks: 13
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Sildurs Enhanced Default v1.071.zip
	OpenGlVersion: 4.5.13537 Compatibility Profile Context 24.20.13001.1010
	OpenGlRenderer: AMD Radeon HD 7900 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 8

**Comment by cleverpanda** [comment]
Fixed
