### ISSUE TITLE
Crash When Mining Redstone

### ISSUE THREAD

**Issue by starfoth** [cleverpanda/Divergent-Underground#8]
I am experiencing a crash when mining Redstone. I have tried disabling any other mods that I can and additionally, have never experienced this issue until using this mod. Also the error log appears to hint that it is this mod that is causing the issue.
Should also mention that I'm very deep at the base of an underground ravine beneath another ravine. It's at the point where my iron pick cannot mine most things so I believe it is the 5x region. Not sure if Redstone mines without crashing at higher levels. 
I think it may be tied to the Redstone attempting to update.
[crash-2019-05-01_18.59.31-client.txt](https://github.com/cleverpanda/Divergent-Underground/files/3136523/crash-2019-05-01_18.59.31-client.txt)

**Comment by cleverpanda** [comment]
What version of the mod are you using

**Comment by starfoth** [comment]
divergentunderground | 0.55.0
Minecraft v 12.2
